development:
  adapter: mysql
  database: viralfeed_development
  pool: 10
  username: root
  password: 
  host: 127.0.0.1
  
test:
  adapter: mysql
  database: viralfeed_test
  pool: 10
  username: root
  password: 
  host: 127.0.0.1

production:
  adapter: mysql
  database: viralfeed_production
  username: root
  password:
  host: 127.0.0.1